### PR TITLE
Added more language definitions and expanded capabilities

### PR DESCRIPTION
**Pull request by ghfbsd**
These changes add vgrind prettyprint support for two more languages:  Fortran 77 and R.

For R support, since the language allows . characters in identifiers, the changes add a new capability to flag this language feature.

Changes to filter mode permit suppressing of the procedure titles in the program listing.

Changed caveats about filter mode in documentation and listed another bug.

Also added "const" keyword to C language definition.

### CODE REVIEW

**Review by rfritz — DISMISSED** [review]
Another language supported! Great!

**Comment by rfritz** [comment]
Thanks for all these changes - I'm surprised anyone else is interested in this venerable command. I'm going to think these over and get back to you. Most of them I like; the .gitignore change bothers me, and I think I'd rather be able to see ^Ms in my code - or are you working with programs that are brought over from Windows?

**Comment by ghfbsd** [comment]
Firstly, thanks for reviving this tool on the mac.

Reason for changes: I need vgrind filter mode to list some code in an academic ms I'm writing.  I used to use it years ago and it still has occasional usefulness.

Regarding ^M: Modern compilers accept either unix or windows style line endings.  For the 1% of code that actually has ^M in a string/char constant somewhere, the change will cause it to disappear; but for the > 50% of code (most is developed on windows) that gets prettyprinted on this vgrind, the user will benefit.  (One of them is me because I collaborate on code maintained on windows.)  It seemed pointless adding a command line option to choose ignoring ^M rather than this simpler change that will work in 99% of use cases.

Regarding .gitignore:  Live and let live.  I don't like or plan on using CMake, so this is a mutual coexistence truce - view the proposed change in that spirit!

**Comment by rfritz** [comment]
Mmmm. That sounds reasonable. I'll be away tomorrow, so I'll probably check this in on Friday.

**Comment by rfritz** [comment]
And, it's checked in.  I'm working on a Homebrew package manager formula for this -- if you're interested, I'll let you know when it's ready.

**Comment by rfritz** [comment]
And…here's the Homebrew formula; just add the rfritz/misc tap, and do "brew install vgrind".

Putting this to bed, I hope.

**Pull request merged**
